(ns euler.problem2)

;;Each new term in the Fibonacci sequence is generated by adding the
;;previous two terms. By starting with 1 and 2, the first 10 terms
;;will be:

;;1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

;;By considering the terms in the Fibonacci sequence whose values do
;;not exceed four million, find the sum of the even-valued terms.

(defn fibseq [n1 n2]
  (lazy-seq (cons n1 (fibseq n2 (+ n1 n2)))))

(defn answer []
  (reduce + (take-while #(<= % 4000000) (filter even? (fibseq 1 2)))))

